### ISSUE TITLE
dr s, sh 8

### ISSUE THREAD

**Issue by veerjd** [veerjd/PolyCalculator#37]
![image](https://github.com/veerjd/PolyCalculator/assets/26885867/dafd48ec-98a2-4140-9439-157a72ea5078)
case: `dr s, sh 8`
actual: `dr -> 20, shaman -> 1`
expected: `dr -> 20, shaman -> dead`

**Comment by veerjd** [comment]
This would be fixed by embedding splash management into the combat calculation, right? @ibratoev

**Comment by ibratoev** [comment]
This is actually not a real bug. Tested in Polytopia and the result was the `actual` here. So it is not really a bug.
@veerjd Close it?

**Comment by veerjd** [comment]
The calc changes 'fixed' it

**Comment by veerjd** [comment]
The calc changes 'fixed' it
